name: 'Telegram Notification'
description: 'Send a notification to Telegram chat in TOML format'
inputs:
  telegram_bot_token:
    description: 'Telegram bot token'
    required: true
  chat_id:
    description: 'Telegram chat ID'
    required: true
  title:
    description: 'Notification title'
    required: true
  message:
    description: 'Notification message'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Send Telegram notification
      shell: bash
      env:
        TELEGRAM_BOT_TOKEN: ${{ inputs.telegram_bot_token }}
        CHAT_ID: ${{ inputs.chat_id }}
        TITLE: ${{ inputs.title }}
        MESSAGE: ${{ inputs.message }}
      run: |
        curl -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
          -H "Content-Type: application/json" \
          -d "{
            \"chat_id\": \"${CHAT_ID}\",
            \"text\": \"[Notification]\\nmessage = \\\"${MESSAGE}\\\"\\ntitle = \\\"${TITLE}\\\"\\n\"
          }"