name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: "*"

jobs:
  test:
    name: Test with Python ${{ matrix.python-version }}
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ['3.12', '3.13']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: pip-${{ hashFiles('**/requirements-dev.txt', '**/pyproject.toml') }}
        restore-keys: |
          pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Run tests (non-macOS)
      run: |
        pytest

  build-macos-app:
    name: Build macOS App Bundle
    runs-on: macos-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build macOS app
      run: |
        cd ${GITHUB_WORKSPACE}
        python setup.py py2app --no-strip

    - name: Create DMG (if available)
      run: |
        if command -v create-dmg &> /dev/null; then
          create-dmg \
            --volname "Local Orchestrator Tray" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 100 \
            --icon "Local Orchestrator Tray.app" 200 190 \
            --hide-extension "Local Orchestrator Tray.app" \
            --app-drop-link 600 185 \
            "Local-Orchestrator-Tray.dmg" \
            "dist/"
        else
          echo "create-dmg not available, skipping DMG creation"
          # Create a simple zip instead
          cd dist && zip -r "../Local-Orchestrator-Tray-macOS.zip" "Local Orchestrator Tray.app"
        fi

    - name: Upload macOS app as artifact
      uses: actions/upload-artifact@v4
      with:
        name: Local-Orchestrator-Tray
        path: |
          Local-Orchestrator-Tray*.dmg
          Local-Orchestrator-Tray-macOS.zip
        retention-days: 30

  notify:
    name: Notify Build Status
    runs-on: ubuntu-latest
    environment: Build
    env:
        CHAT_ID: -1002443591493
    needs: [test, build-macos-app]
    if: always()
    
    steps:
    - name: Notify success
      if: needs.test.result == 'success' && needs.build-macos-app.result == 'success'
      uses: ${GITHUB_WORKSPACE}/.github/actions/telegram-notify
      with:
        telegram_bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        chat_id: ${{ env.CHAT_ID }}
        title: "✅ Build succeeded"
        message: "Build on ${{ github.base_ref }} was successful"

    - name: Notify failure
      if: needs.test.result == 'failure' || needs.build-macos-app.result == 'failure'
      uses: ${GITHUB_WORKSPACE}/.github/actions/telegram-notify
      with:
        telegram_bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        chat_id: ${{ env.CHAT_ID }}
        title: "❌ Build failed"
        message: "Build on ${{ github.base_ref }} failed"
